export const INVALIDATE_CHARACTERS = 'INVALIDATE_CHARACTERS';
export const LOAD_CHARACTERS = 'LOAD_CHARACTERS';
export const RECEIVE_CHARACTERS = 'RECEIVE_CHARACTERS';
export const RECEIVE_CHARACTER = 'RECEIVE_CHARACTER';

export const INVALIDATE_STARSHIPS = 'INVALIDATE_STARSHIPS';
export const LOAD_STARSHIPS = 'LOAD_STARSHIPS';
export const RECEIVE_STARSHIPS = 'RECEIVE_STARSHIPS';
export const RECEIVE_STARSHIP = 'RECEIVE_STARSHIP';
